-- 0. Create schema TMS if not exists
CREATE SCHEMA IF NOT EXISTS TMS;

-- 1. Translation Table
CREATE TABLE IF NOT EXISTS TMS.TRANSLATION (
    ID BIGSERIAL PRIMARY KEY,
    TRANSLATION_KEY VARCHAR(200) NOT NULL,
    LOCALE VARCHAR(50) NOT NULL,
    CONTENT TEXT
    CONSTRAINT uq_translation_key_locale UNIQUE (TRANSLATION_KEY, LOCALE)
);

CREATE INDEX idx_translation_key ON TMS.TRANSLATION(TRANSLATION_KEY);
CREATE INDEX idx_translation_locale ON TMS.TRANSLATION(LOCALE);

-- 2. Tag Table
CREATE TABLE IF NOT EXISTS TMS.TAG (
    ID BIGSERIAL PRIMARY KEY,
    TAG_NAME VARCHAR(100) NOT NULL UNIQUE
);

CREATE INDEX idx_tag_name ON TMS.TAG(TAG_NAME);

-- 3. Translation-Tag Mapping Table
CREATE TABLE IF NOT EXISTS TMS.TRANSLATION_TAG_MAPPING (
    ID BIGSERIAL PRIMARY KEY,
    TRANSLATION_ID BIGINT NOT NULL,
    TAG_ID BIGINT NOT NULL,
    CONSTRAINT fk_translation FOREIGN KEY (TRANSLATION_ID) REFERENCES TMS.TRANSLATION(ID) ON DELETE CASCADE,
    CONSTRAINT fk_tag FOREIGN KEY (TAG_ID) REFERENCES TMS.TAG(ID) ON DELETE CASCADE
);

-- 4. User Table (renamed to avoid reserved keyword)
CREATE TABLE IF NOT EXISTS TMS.APP_USER (
    ID BIGSERIAL PRIMARY KEY,
    USERNAME VARCHAR(100) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL
);
